# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blake Curry
email: blake.curry@gmx.us
description: > # this means to ignore newlines until "baseurl:"
  This is a Portfolio site for Blake Curry(a.k.a. Faxn).

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://faxn.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown


permalink: /:categories/:title:output_ext

#Google analytics tracking id
ga_id: UA-97202752-1

favicon: https://avatars3.githubusercontent.com/u/3074727?v=3
usecdn: true

collections:
    projects:
        output: true

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: /:collection/:name:output_ext
 
social_links:
-
    name: Email
    fa-icon: fa-envelope
    url: mailto:blake.curry@gmx.us
-
    name: Github
    icon: //github.com/favicon.ico # TODO Self-host social media icons insted of hotlinking
    #icon: static/icon-github.svg
    fa-icon: fa-github
    url: //www.github.com/faxn
-
    name: Linkedin
    fa-icon: fa-linkedin
    icon: https://www.linkedin.com/favicon.ico
    url: https://www.linkedin.com/in/blake-curry-27163331
-
    name: freeCodeCamp
    fa-icon: fa-free-code-camp
    url: https://www.freecodecamp.org/faxn
